apiProject/apiApk/urls.py
from django.urls import path 
from . import views 

app_name = 'apiApk'
urlpatterns = [
  path('create-user', views.asyncCreateUser, name='create-user'),
  path('conpte', views.conpte),
    
]

apiProject/apiProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apiApk.urls')),
]

apiProject/apiApk/views.py
import json
from django import views
from django.http import JsonResponse
from django.shortcuts import redirect, render
import requests 
from rest_framework.decorators import api_view
@api_view(['POST'])
def asyncCreateUser(request):
    if request.method == "POST":
        data = request.data
        kmail_user = requests.post('http://kmail.africa/signup', json=data)
        klapeers_user = requests.post('http://klapeers.com/signup', json=data)
        
        if kmail_user.status_code == 200 and  klapeers_user.status_code == 200:
            return JsonResponse({"status":200, "result": "success", "msg": "Compte cree avec success"})
        else:
            return JsonResponse({"kmail_error": kmail_user.json(), "klapeers_error": klapeers_user.json()})
      
def conpte(request):
    return render(request, 'compte.html')

apiProject/apiApk/templates/compte.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
   <form method='POST' action="{% url 'apiApk:create-user' %}">
<label for="name">name</label>
<input type="text" id="name">
<input type="submit" value='send'>
   </form>
    </body>
</html>